# Generated by Django 2.2.1 on 2019-05-29 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru_name', models.CharField(max_length=100)),
                ('en_name', models.CharField(max_length=100)),
                ('is_prose', models.NullBooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru_name', models.CharField(max_length=100)),
                ('en_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru_name', models.CharField(max_length=250, null=True)),
                ('en_name', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inspiration',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aconite_app.Book')),
            ],
            bases=('aconite_app.book',),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='aconite_app.Person'),
        ),
        migrations.AddField(
            model_name='book',
            name='languages',
            field=models.ManyToManyField(to='aconite_app.Language'),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aconite_app.Book')),
                ('original_title', models.CharField(max_length=1000, null=True)),
                ('dedication', models.CharField(max_length=1000, null=True)),
                ('year_demo', models.CharField(max_length=250, null=True)),
                ('year', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('day', models.IntegerField(null=True)),
                ('is_translation', models.BooleanField()),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aconite_app.Genre')),
                ('inspirations', models.ManyToManyField(to='aconite_app.Inspiration')),
                ('locations', models.ManyToManyField(to='aconite_app.Location')),
            ],
            bases=('aconite_app.book',),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, null=True)),
                ('dedication', models.CharField(max_length=1000, null=True)),
                ('text', models.TextField()),
                ('num_part', models.IntegerField()),
                ('work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aconite_app.Work')),
            ],
        ),
    ]
