# Generated by Django 2.2.1 on 2019-05-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aconite_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='is_prose',
            field=models.NullBooleanField(default=None),
        ),
    ]
