# Generated by Django 2.2.1 on 2019-05-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aconite_app', '0002_genre_is_prose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='day',
        ),
        migrations.RemoveField(
            model_name='content',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='content',
            name='month',
        ),
        migrations.RemoveField(
            model_name='content',
            name='year',
        ),
        migrations.AddField(
            model_name='work',
            name='day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='locations',
            field=models.ManyToManyField(to='aconite_app.Location'),
        ),
        migrations.AddField(
            model_name='work',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
