# Generated by Django 2.2.1 on 2019-05-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aconite_app', '0004_auto_20190519_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='original_title',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
