# Generated by Django 2.2.1 on 2019-05-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aconite_app', '0005_content_original_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='original_title',
        ),
        migrations.AddField(
            model_name='work',
            name='original_title',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
