# Generated by Django 2.2.1 on 2019-05-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aconite_app', '0006_auto_20190519_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='languages',
        ),
        migrations.AddField(
            model_name='book',
            name='languages',
            field=models.ManyToManyField(to='aconite_app.Language'),
        ),
    ]
