# Generated by Django 2.2.1 on 2019-05-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aconite_app', '0008_auto_20190519_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
